### ISSUE TITLE
Problem on Homey Pro 2023

### ISSUE THREAD

**Issue by dwgreven** [rjoomen/com.bluesound#14]
I did a restore from a backup from my older Homey Pro. De BlueSound Soundbar and the bluesound-app were restored, but not working.
The soundbar gives the message no app installed.
I have the app deleted and wanted to install it from the appstore, that didn’t happen.
So i deleted the soundbar and wanted to do a fresh start: i can not install the bluesound app from the appstore.
Please help.

**Comment by eddiegonzales** [comment]
I have the same problem. I am also not able to install it after i have deletede it on the new Homey Pro 2023. It appaers in the app list right after install, but going out of the Homey App on iphone, it dissappears again.

**Comment by dwgreven** [comment]
I see the same: install the app, it is visible for a few seconds in the app-list from the Homey Pro and then it disappears.

**Comment by roelofoomen** [comment]
The last version has fixed a lot of crashes, how does the app work for you now?

**Comment by dwgreven** [comment]
For me it works top!
