### ISSUE TITLE
Volume problem (results in speaker damage!!)

### ISSUE THREAD

**Issue by JeroenAJ** [rjoomen/com.bluesound#7]
Hello bluesound app for homey creator(s),
I just blown up my speakers (worth €4600) through my new NAD M33 Bluesound integrated amplifier.
This happened, after I wanted to step up the volume through the Homey app this way:

Homey > Device > NAD M33 (Bluesound app) > Volume bar > "+" sign

Apparently the "+" means MAX and the "-" means MUTE (although the next page shows a "mute"-button)
At the moment I pushed "+", there was music playing from my M33, at the moment the volume went from 40% to FULL power, my speakers could not handle the insane increase.

This problem needs to be resolved AS QUICK AS POSSIBLE!
Thank me.

**Comment by JeroenAJ** [comment]
After some research, found that the "relative volume bar" works the same as for light brightness.
BUT, for the light there is a different icon witch stands for Full-on and OFF.

The most easy repair can be to replace "+" and "-" for "MAX" and "MIN"(or "MUTE").
Only thing I want to say is, this relative volume bar is really dangerous.
Luckily my ears are still OK, but the material damage is done.

**Comment by jghaanstra** [comment]
Sorry to hear about the material damage but I have no control over how Athom chooses to display the volume functionality within the mobile app. I just implement the capabilities volume_set and volume_mute. You should report this to Athom.
